# -*- coding: utf-8 -*-
"""nyc_flood_cascade_gnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mwlLUbIDKutqh605XAJIGMluDpp2UwjJ
"""

"""
NYC Flood → Substations → Cascade Simulation → GNN Prediction

Data Sources:
- NYC Flood Hazard GeoJSON
- OpenStreetMap NYC Power Infrastructure (OSMnx)

Pipeline:
Loads Flood GIS → Download Real Substations → Spatial Join →
Builds Infrastructure Graph → Cascade Simulation →
Trains GNN → Predict Failure Risk

Author : Shreyansh Saurabh
"""

#!pip install torch torchvision torchaudio
#!pip install torch-geometric
#!pip install geopandas rasterio shapely networkx pandas numpy matplotlib osmnx

import geopandas as gpd
import networkx as nx
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn.functional as F
import osmnx as ox

from shapely.geometry import Point
from torch_geometric.utils import from_networkx
from torch_geometric.nn import GCNConv

from google.colab import drive
drive.mount('/content/drive')

flood = gpd.read_file(
"/content/drive/MyDrive/flood_project/nyc_flood_dataset.geojson"
)
print("Loaded Flood Dataset")
print(flood.head())
print("CRS:", flood.crs)

"""
Visualizing flood polygons
"""

flood.plot(figsize=(8,8))
plt.title("NYC Flood Hazard")
plt.show()

"""
Downloading NYC power substations and infrastructure from OpenStreetMap
"""

place = "New York City, New York, USA"

tags = {
    "power": ["substation", "plant", "transformer"]
}

power_raw = ox.features_from_place(place, tags)

print("Power assets downloaded:", len(power_raw))
power_raw.head()

"""
Converts substations / plants to centroid points
"""

power_points = power_raw.copy()
power_points["geometry"] = power_points.geometry.centroid
power_points = power_points[["geometry"]].reset_index(drop=True)

"""
Ensures CRS alignment before spatial join
"""

power_points = power_points.set_crs("EPSG:4326", allow_override=True)
power_points = power_points.to_crs(flood.crs)

"""
Maps flood exposure to real substations
"""

power_flood = gpd.sjoin(
power_points,
flood,
how="left",
predicate="intersects"
)

power_flood["flood_exposed"] = power_flood.index_right.notnull().astype(int)

print(power_flood.head())

"""
Builds graph by connecting nearby substations
"""

coords = np.array([
(p.x, p.y) for p in power_flood.geometry
])

G = nx.Graph()

for i in range(len(coords)):
    G.add_node(i)

threshold = 0.02

for i in range(len(coords)):
    for j in range(i+1, len(coords)):
        dist = np.linalg.norm(coords[i]-coords[j])
        if dist < threshold:
            G.add_edge(i,j)

print("Graph Nodes:", G.number_of_nodes())
print("Graph Edges:", G.number_of_edges())

"""
Attaches flood exposure + synthetic load features
"""

for i,node in enumerate(G.nodes()):
    G.nodes[node]["flood"] = power_flood.iloc[i]["flood_exposed"]
    G.nodes[node]["load"] = np.random.uniform(0.5,1.5)

"""
Simulates cascading failures triggered by flood exposure
"""

def simulate_cascade(G):

    failed=set()

    for node in G.nodes():
        if G.nodes[node]["flood"]==1:
            if np.random.rand()<0.5:
                failed.add(node)

    changed=True
    while changed:
        changed=False
        for node in G.nodes():
            if node in failed: continue

            neigh=list(G.neighbors(node))
            f=sum([1 for n in neigh if n in failed])

            if f>0 and np.random.rand()<0.2*f:
                failed.add(node)
                changed=True

    return failed

"""
Generates failure labels from cascade simulation
"""

labels=np.zeros(len(G.nodes()))
failed=simulate_cascade(G)

for node in failed:
    labels[node]=1

"""
Converts graph + features to GNN training format
"""

for node in G.nodes():
    G.nodes[node]["feature"]=[
        G.nodes[node]["flood"],
        G.nodes[node]["load"]
    ]

data=from_networkx(G)

data.x=torch.tensor(
[G.nodes[n]["feature"] for n in G.nodes()],
dtype=torch.float
)

data.y=torch.tensor(labels,dtype=torch.long)

"""
Graphs Neural Network for failure prediction
"""

class GNN(torch.nn.Module):

    def __init__(self):
        super().__init__()
        self.conv1=GCNConv(2,16)
        self.conv2=GCNConv(16,2)

    def forward(self,data):
        x,edge=data.x,data.edge_index
        x=self.conv1(x,edge)
        x=F.relu(x)
        x=self.conv2(x,edge)
        return x

"""
Trains GNN model
"""

model=GNN()
opt=torch.optim.Adam(model.parameters(),lr=0.01)

for epoch in range(100):
    opt.zero_grad()
    out=model(data)
    loss=F.cross_entropy(out,data.y)
    loss.backward()
    opt.step()

    if epoch%10==0:
        print(epoch,loss.item())

"""
Predicts failure probability for each infrastructure node
"""

model.eval()
pred=model(data)
prob=torch.softmax(pred,dim=1)

print("Failure Probabilities:")
print(prob[:10])

"""
Ploting histogram of predicted failure probabilities
"""

fail_prob = prob[:,1].detach().numpy()

plt.hist(fail_prob, bins=20)
plt.title("Distribution of Failure Risk")
plt.xlabel("Failure Probability")
plt.ylabel("Number of Substations")
plt.show()

print(flood.columns)

"""
Creating Flood Probability Map

Uses: FVI_storm_surge_present
"""

import pandas as pd
import matplotlib.pyplot as plt

score = pd.to_numeric(
    flood["FVI_storm_surge_present"],
    errors="coerce"
)

score = score.fillna(score.mean())
flood["flood_prob"] = (score - score.min()) / (score.max() - score.min())


flood.plot(
    column="flood_prob",
    cmap="Reds",
    legend=True,
    figsize=(8,8)
)

plt.title("NYC Flood Probability (Storm Surge Present)")
plt.show()

